### ISSUE TITLE
queryParams in Popup not uri-component encoded

### ISSUE THREAD

**Issue by simoneggler** [SchweizerischeBundesbahnen/scion-workbench#109]
## Current behavior
queryParams containing '&' characters mess up the components path

## Expected behavior
queryParams are encoded with encodeURIComponent()

## Minimal reproduction of the problem with instructions
open a popup with queryParams containing '&'

` const qualifier: Qualifier = { entity: 'sample' };
   const popup: Popup = {
      position: 'east',
      anchor: event.target as Element,
      queryParams: {aVariable: 'a & b', bVariable: 'c'}
    };
    this.popupService.open(popup, qualifier);`

the receiving popup component will not receive variables values for 'aVariable' and 'bVariables' as given above. instead 'aVariable' contains 'a ', 'bVariable' is undefined

## Environment
- SCION Workbench version: 0.0.0-beta.15
- Angular version: 7

**Comment by danielwiehl** [comment]
Solved with the new microfrontend integration
