### ISSUE TITLE
Allow registering view and popup capabilities as viewpart actions

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#114]
## Is your feature request related to a problem? Please describe.
The workbench allows registering viewpart actions, e.g. to open a view or popup. This should also be possible for micro frontends installed in the platform.

**Comment by danielwiehl** [comment]
We defer this issue until we have a concept how to contribute `view-local` and `application-local` viewpart actions.

**Comment by helios57** [comment]
This issue is obsolete with the new concept.
