### ISSUE TITLE
Demo links in scion-workbench-demo do not work

### ISSUE THREAD

**Issue by judithgull** [SchweizerischeBundesbahnen/scion-workbench#146]
## Current behavior

In **scion-workbench-demo** the links in the readme point to 
https://blog.sbb.technology/scion-workbench-demo/#/... which seem to be broken.

In https://github.com/SchweizerischeBundesbahnen/scion-workbench/blob/master/resources/site/workbench.md the link works.(https://schweizerischebundesbahnen.github.io).

## Expected behavior
demo should be reachable

## Environment
- SCION Workbench version: 0.0.0

**Comment by danielwiehl** [comment]
Fixed
