### ISSUE TITLE
macOS keyboard support: Add support for command key + click to open link in new workbench tab

### ISSUE THREAD

**Issue by jgsbb** [SchweizerischeBundesbahnen/scion-workbench#155]
## Is your feature request related to a problem? Please describe.
On macOS i cannot open a link in a new workbench tab by pressing command key.

## Describe the solution you'd like
On macOS command+click opens a link in a new workbench tab like Ctrl+click on Windows.

Thx mate! ;)

**Comment by danielwiehl** [comment]
Thank you @jgsbb for filing this issue. Please provide us with a pull request. Otherwise, we will address this issue when implementing multi-browser support, which will be by the end of this year.
