### ISSUE TITLE
Add support for Angular 9.x

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#197]
## Is your feature request related to a problem? Please describe.
SCION Workbench and SCION Workbench Application Platform supports Angular 8.x.

## Describe the solution you'd like
Update SCION Workbench and SCION Workbench Application Platform to run with Angular 9.x.

## Additional context
- drop support for Angular 8.x
- upgrade demo-apps to Angular 9.x

**Comment by helios57** [comment]
Todo after upgrade to 9:

Package "tsickle" has an incompatible peer dependency to "typescript" (requires "~3.4.1", would install "3.6.4").
npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN codelyzer@5.1.0 requires a peer of @angular/compiler@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.1.0 requires a peer of @angular/core@>=2.3.1 <9.0.0 || >8.0.0-beta <9.0.0 || >8.1.0-beta <9.0.0 || >8.2.0-beta <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.35.0 requires a peer of typescript@~3.4.1 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.3.4 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.

            ⮑   projects\app\workbench-application-platform\contact-app\src\app\contact\contact-activity\contact-activity.component.ts@23:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\contact-app\src\app\contact\contact-new-popup\contact-new-popup.component.ts@32:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\contact-app\src\app\contact\contact-view\contact-view.component.ts@34:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\contact-app\src\app\contact\related-contact-add-popup\related-contact-add-popup.component.ts@24:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\communication-app\src\app\communication\communication-view\communication-view.component.ts@24:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\communication-app\src\app\communication\communication-new-popup\communication-new-popup.component.ts@31:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\dev-tools-app\src\app\dev-tools\application-view\application-view.component.ts@24:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\dev-tools-app\src\app\dev-tools\outlet-capability-exec-popup\outlet-capability-exec-popup.component.ts@30:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-c985a55b\view-c985a55b.component.ts@19:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\testing-view\testing-view.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-0c4fe9e3\view-0c4fe9e3.component.ts@20:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\testing-popup\testing-popup.component.ts@25:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\testing-activity\testing-activity.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-354aa6da\view-354aa6da.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-85dde646\view-85dde646.component.ts@17:15: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-56657ad1\view-56657ad1.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-c8e40918\view-c8e40918.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-a686d615\view-a686d615.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-4a4e6970\view-4a4e6970.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-608aa47c\view-608aa47c.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-f389a9d5\view-f389a9d5.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-b1dd152a\view-b1dd152a.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-ffd6a78f\view-ffd6a78f.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-cc977da9\view-cc977da9.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-b6a8fe23\view-b6a8fe23.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-28f32b51\view-28f32b51.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-1a90c8d2\popup-1a90c8d2.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-7330f506\popup-7330f506.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-9c5319f7\popup-9c5319f7.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-45dc693f\popup-45dc693f.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-f4286ac4\popup-f4286ac4.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-159913ad\popup-159913ad.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-8a468258\popup-8a468258.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-fc077b32\popup-fc077b32.component.ts@19:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\popup-5782ab19\popup-5782ab19.component.ts@19:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-5782ab19\view-5782ab19.component.ts@19:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-68f302b4\view-68f302b4.component.ts@23:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\activity-4a3a8984\activity-4a3a8984.component.ts@20:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\activity-28f32b51\activity-28f32b51.component.ts@21:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-be587bd6\view-be587bd6.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\activity-6d806bea\activity-6d806bea.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\activity-5782ab19\activity-5782ab19.component.ts@19:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-c91805e8\view-c91805e8.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-cba33eaf\view-cba33eaf.component.ts@18:5: Provider is not statically analyzable.
            ⮑   projects\app\workbench-application-platform\testing-app\src\app\testing\view-b8bbbb11\view-b8bbbb11.component.ts@18:5: Provider is not statically analyzable.
