### ISSUE TITLE
Unregister a capability by its type and qualifier instead of its id

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#199]
## Current behavior
To unregister a capability, the capability must first be fetched in order to get its id. The id is then used to unregister the capability.

## Expected behavior
Instead, a capability should be unregistered by providing its type and qualifier. 

## Environment
- SCION Workbench version: 0.0.0-beta.29
- Angular version: 8.x

**Comment by mofogasy** [comment]
What if - by accident or on purpose - two capabilities of the same type and qualifier exists? Should both be deleted?

**Comment by danielwiehl** [comment]
You can unregister only capabilities of your own application which typically have unique qualifiers. So yes, both should be unregistered.
