### ISSUE TITLE
Implicit intent is not removed when unregistering a capability

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#200]
## Current behavior
When registering a capability, it automatically gets an implicit intent so that the providing app can use it without having to declare an intent. But, when unregistering a capability, its implicit intent is not removed.

## Expected behavior
The implicit intent is also removed when unregistering a capability.

## Environment
- SCION Workbench version: 0.0.0-beta.29
- Angular version: 8.x

**Comment by mofogasy** [comment]
Should this be public API?

**Comment by danielwiehl** [comment]
Unregistering some capability should also remove its implicit intent, no public API required for that. Or what exactly do you mean?

**Comment by mofogasy** [comment]
I thought that registering intents was public API (like for registering capabilities dynamically). If that was the case, it should also be possible to unregister intents. But I was mistaken, as registering intents is not possible other than by declaring them in the manifest...
