### ISSUE TITLE
View tab receiving dblclick event

### ISSUE THREAD

**Issue by mofogasy** [SchweizerischeBundesbahnen/scion-workbench#24]
## Current behavior
When closing two (or more) view tabs in quick succession, a dblclick event is fired and delivered to the second view tab, which toggles the maximize mode of the main content.

## Expected behavior
When clicking in quick succession to close view tabs, the tabs should be closed without toggling maximize mode (or if tabs have different widths, then the next tab should be activated).

## Minimal reproduction of the problem with instructions
Plunkr that demonstrates how an element receives a dblclick event, even though only clicked once:
https://plnkr.co/edit/vrUVABv25rwhtnXxrw8F?p=preview

Reproduce in SCION - Angular Workbench Demo
1. Go to https://blog.sbb.technology/scion-workbench-demo/#/(view.6:person/69//view.5:person/75//view.4:person/9//view.3:person/54//activity:person-list)?viewgrid=WyJ2aWV3cGFydC4xIiwidmlldy4zIiwidmlldy4zIiwidmlldy40Iiwidmlldy41Iiwidmlldy42Il0%3D
2. Double-click on the 'x' of the first tab
3. Tab is closed, but at the same time, the content is maximized

## Environment
- SCION Workbench version: 0.0.0-beta.10

**Comment by danielwiehl** [comment]
Thank you for submitting this pull request and welcome to our community. We are excited to review your changes, and you should get some feedback from us soon.

**Comment by danielwiehl** [comment]
Merged into master. Thank you @mofogasy for your contribution.
