### ISSUE TITLE
Lifecycle hook `wbBeforeDestroy` is not called for views of lazily loaded modules

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#27]
## Current behavior
Lifecycle hook `wbBeforeDestroy` is not called for views of lazily loaded modules.

Also, the title and heading are not set if they are configured on the route.

## Expected behavior
Lifecycle hook is called.

## Minimal reproduction of the problem with instructions

1. Create a lazily loaded module
2. Create a view in that module
3. Implement lifecycle hook `wbBeforeDestroy` in that view
4. Close the view

## Environment
- SCION Workbench version: 0.0.0-beta.10
- Angular version: 6.0.2

**Comment by mofogasy** [comment]
This problem might be related to https://github.com/angular/angular/issues/28730

**Comment by danielwiehl** [comment]
The workbench installs a `CanDeactivate` guard to prevent a view from being closed.

This currently leads to the following problems:
- The guard is not invoked for certain route configurations (works for `component` and `loadComponent`, but not for `children` and `loadChildren`).
- The workbench router must perform a separate navigation for each view that is to be closed. Otherwise, the entire navigation would be canceled if some view(s) prevent closing. In addition, the separate navigations each cause an entry in the browsing history.

We should consider a different approach to prevent views from closing.
