### ISSUE TITLE
Allow configuring brokerDiscoverTimeout and deliveryTimeout

### ISSUE THREAD

**Issue by adriansacchi** [SchweizerischeBundesbahnen/scion-workbench#286]
## Is your feature request related to a problem? Please describe.
MicroApplicationConfig allows for configuring brokerDiscoverTimeout and deliveryTimeout, but for the scion-workbench these settings are not exposed.

When a contributed micro-frontend has higher values set and effectively causes high load on the message bus the host-application itself could experience the following error while publishing messages.

'[MessageDispatchError] Broker did not report message delivery state within the 10000ms timeout.'

## Describe the solution you'd like
Allow for configuring these timeouts also for the host-application. 

It is obvious that higher timeout values do not really solve the underlying problem. But still it would be appreciated when the host-application could be configured in accordance with the contributed microfrontends.

## Additional context
Addressing the underlying performance problem an issue has been opend for scion-microfrontend-platform:
https://github.com/SchweizerischeBundesbahnen/scion-microfrontend-platform/issues/90

**Comment by danielwiehl** [comment]
Thank you @adriansacchi for filing this issue.
