### ISSUE TITLE
Workbench Router sometimes opens wrong microfrontend views

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#311]
## Describe the bug
We have noticed that the Workbench Microfrontend Router sometimes opens the wrong microfrontend view when navigating quickly.

## Expected behavior
The Workbench Microfrontend Router should always open the correct view as specified in the qualifier.

## Additional context
 - SCION Workbench version: `12.0.0-beta.1`
 - SCION Workbench Client version: `1.0.0-beta.7`
 - SCION Microfrontend Platform version: `1.0.0-beta.19`

**Comment by k-genov** [comment]
Cannot be reproduced anymore. Please open a new issue if this happens again.
