### ISSUE TITLE
Params with undefined value in URL

### ISSUE THREAD

**Issue by delta-peg** [SchweizerischeBundesbahnen/scion-workbench#325]
## Describe the bug
When using WorkbenchRouter to navigate to a microfrontend, and supplying a params-Map which contains key-value pairs with `undefined` value, these params are listed in the URL queryParams as "...;key=undefined;..."
This leads to parse errors when trying to JSON.parse the URL State

## To Reproduce

1. Use a WorkbenchRouter to navigate to a capability with optional parameters. Submit value `undefined` for these optional parameters to the navigate() call
2. Check the browser URL for these parameter values
3. The params are listed in the URL with value undefined

## Expected behavior
3. params with value undefined are not listed in the browser URL

## Screenshots
Example: from the szenario view in capaplan, open a ZWL directly from the developer-pane on the left (opened with Ctrl+Shift+F)
Several queryParams with value undefined are listed in the resulting URL.
![image](https://user-images.githubusercontent.com/76786626/159509980-90920a14-800e-4771-b548-fb724d8ae59b.png)

## Environment
Please complete the following information:

 - SCION Workbench Client version: 1.0.0-beta.8
 - Angular version: 12.4.0
 - Browser: Edge 99.0.1150.46 
 - OS: Windows 10
 - Device: Desktop

**Comment by danielwiehl** [comment]
This bug is caused due to the following issue in the SCION Microfrontend Platform: SchweizerischeBundesbahnen/scion-microfrontend-platform#146. However, for greater robustness, we should also detect and remove such parameters in the Workbench.
