### ISSUE TITLE
Prevent closing a view if it displays a message box with view modality

### ISSUE THREAD

**Issue by mofogasy** [SchweizerischeBundesbahnen/scion-workbench#344]
## Describe the bug
When a message box with view modality is open in a view, it should not be possible to close the view.
Right now, the view cannot be closed through the keystroke `Ctrl+k` or the close button (`x`) of the tab (since it is hidden), which is the correct behavior.
However, the view can still be closed through the context menu of its tab (`Close tab` and `Close all tabs`), which is wrong.

## To Reproduce

1. Go to the [Testing App](https://scion-workbench-testing-app.vercel.app/)
2. Click on 'Workbench Messagebox'
3. Click on 'Open message box' button
4. Right-click on the tab
5. The context menu entries `Close tab` and `Close all tabs` are active and can be used to close the tab.

## Expected behavior
The context menu entries `Close tab` and `Close all tabs` should be inactive.

## Environment
Please complete the following information:

 - SCION Workbench version: [13.0.0-beta.2]
 - SCION Workbench Client version: [1.0.0-beta.10]
 - Angular version: [13.3.4]
 - Browser: [Chrome 104]
 - OS: [Windows 10]
 - Device: [Desktop]

**Comment by danielwiehl** [comment]
If fixed we can enable the test `message-box.e2e-spec.ts`: `should prevent closing a view if it displays a message box with view modality`
