### ISSUE TITLE
Workbench modules should be released automatically on a tag

### ISSUE THREAD

**Issue by ReToCode** [SchweizerischeBundesbahnen/scion-workbench#56]
Workbench modules should be released automatically on a tag.

## Describe the solution you'd like
Travis build should release npm artifacts.

**Comment by danielwiehl** [comment]
As of now, releasing to NPM registry is a manual task which should be automated.

The process is described in our Release Guidelines.

If pushing a Git release tag (e.g. `2.0.0-beta.0`, `2.0.0-beta.1`, `2.0.0-rc.0`, `2.0.0`), all SCION projects should be built and published to NPM. Pre-releases should be tagged with the distribution tag next, and stable releases with latest.

The generation of the changelog must not be automated yet.
