### ISSUE TITLE
Message not shown in messagebox in microfrontend context

### ISSUE THREAD

**Issue by erard22** [SchweizerischeBundesbahnen/scion-workbench#591]
## Describe the bug
Sending a messagebox intent to the host application, the message is not displayed in the dialog box, only the header

## To Reproduce
Send intent using this code: 

```
async canClose(): Promise<boolean> {
    const action = await this.messageBoxService.open('bar', {
      title: 'foo',
      actions: { yes: 'yes', no: 'no'}
    })
    return action === 'yes';
  }
```

## Expected behavior
Message should be shown, in my simple example: `bar`

## Screenshots

![image](https://github.com/user-attachments/assets/8906ebd5-93a1-4ba2-b2b9-ffde7694025a)

## Environment
Please complete the following information:

 - SCION Workbench version: 18.0.0-beta.3
 - SCION Workbench Client version: 1.0.0-beta.24
 - Angular version:18
 - Browser: Chrome
 - OS: Windows and MacOS
 - Device: Desktop
 - 
## Additional context
Example code you find here: https://github.com/erard22/bison-microfrontend-apps

**Comment by danielwiehl** [comment]
Thank you @erard22 for reporting this bug. We are investigating the problem and will provide a fix soon.

**Comment by erard22** [comment]
works like a charm. Thanks.
