### ISSUE TITLE
Allow generating the changelog based on the project's commit messages

### ISSUE THREAD

**Issue by danielwiehl** [SchweizerischeBundesbahnen/scion-workbench#68]
## Is your feature request related to a problem? Please describe.
Changelog must be manually completed when preparing the release commit in order to publish a new NPM release.

## Describe the solution you'd like
Allow generating the changelog based on the project's commit messages. The changelog should have the same format as the changelog used by the Angular project.

Generation of the changelog should still be triggered manually when preparing the release commit to publish a new NPM release.

## Additional context
[conventional-changelog-angular](https://www.npmjs.com/package/conventional-changelog-angular)

**Comment by ReToCode** [comment]
To achieve this, we will rewrite the entire history of the repository with the angular message commit style. Then the change log can be re-generated from the first release.

**Caution:**
- All the git hashes will change
- The already released npm packages will not be rebuilt, thus the commit hash will not match any longer
