### ISSUE TITLE
View tab activation history

### ISSUE THREAD

**Issue by mofogasy** [SchweizerischeBundesbahnen/scion-workbench#74]
## Is your feature request related to a problem? Please describe.
When closing an active view tab, the tab next to it is activated by default. This can be confusing to the user, especially if the newly activated tab hasn't been used for a while.

## Describe the solution you'd like
Keep track of the order the tabs have been activated. When an active tab is closed, the tab which was active before will be activated again, and so on when that tab is closed.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by danielwiehl** [comment]
Thank you for your issue and PR which will improve the user experience strongly. We will have a look at it soon.
