### ISSUE TITLE
Demo app is hosted on untrusted site

### ISSUE THREAD

**Issue by simoneggler** [SchweizerischeBundesbahnen/scion-workbench#94]
## Current behavior
browser shows ssl warning when opening demo site : 
https://blog.sbb.technology/scion-workbench-demo/

## Expected behavior
browser shows demo without warning

## Minimal reproduction of the problem with instructions
point your browser to: https://blog.sbb.technology/scion-workbench-demo/ and see error.

**Comment by simoneggler** [comment]
the link is found here: https://github.com/SchweizerischeBundesbahnen/scion-workbench/blob/master/resources/site/workbench.md

**Comment by danielwiehl** [comment]
Thank you Simon, we are going to fix it!
