### ISSUE TITLE
Default Activity

### ISSUE THREAD

**Issue by simoneggler** [SchweizerischeBundesbahnen/scion-workbench#95]
## Is your feature request related to a problem? Please describe.
my application always opens with a blank screen, that's very annoying.

## Describe the solution you'd like
i would like to declare a fallback activity that open per default.

**Comment by danielwiehl** [comment]
Thank you Simon for your input, good point! We are working on a feature which allows specifying kind of an entry point when no view is showing.

As of now, you can configure a route which redirects to your activity component as follows:

```
RouterModule.forRoot([
  {path: 'your-activity', component: YourActivityComponent},
  {path: '', redirectTo: '/(activity:your-activity)', pathMatch: 'full'},
]),
```
Then, however, you cannot close the activity anymore. Using an URL matcher has the limitation that you cannot inject the `Router` to query the initial navigational state. A hacky workaround would be by checking some static accessor whether the initial navigation is over.

In Routing module, add the following route and matcher function:

```
RouterModule.forRoot([
  {path: 'your-activity', component: YourActivityComponent},
  {matcher: initialEmptyPathMatcher, redirectTo: '/(activity:your-activity)'},
]),

export function initialEmptyPathMatcher(segments: UrlSegment[], group: UrlSegmentGroup, route: Route): UrlMatchResult {
  // check if not navigated yet and if the path is empty
  if (!(document as any).navigated() && segments.length === 0) {
    return {consumed: segments};
  }
  return null;
}
```

In `app.component.ts` add the following constructor:

```
@Component({selector: 'app-root', templateUrl: './app.component.html'})
export class AppComponent {
  constructor(router: Router) {
    (document as any).navigated = (): boolean => router.navigated;
  }
}
```

**Comment by danielwiehl** [comment]
See issue #105
